#!/bin/bash
# Setup script for Voice Assistant Pi Client systemd service
# Run with: sudo ./setup_pi_service.sh install
# Remove with: sudo ./setup_pi_service.sh uninstall

set -e

SERVICE_NAME="voice-assistant"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
JOURNAL_CONF="/etc/systemd/journald.conf.d/voice-assistant.conf"
ENV_FILE="/etc/voice-assistant.env"

# Detect current user (the one who invoked sudo)
if [ -n "$SUDO_USER" ]; then
    ACTUAL_USER="$SUDO_USER"
else
    ACTUAL_USER="$(whoami)"
fi

# Default paths - adjust if needed
INSTALL_DIR="/home/${ACTUAL_USER}/voice-assistant-2"
VENV_PATH="${INSTALL_DIR}/venv"
ENTITIES_PATH="/home/${ACTUAL_USER}/.cache/ha_entities.json"

# Default configuration
JETSON_HOST="192.168.1.117"
JETSON_PORT="8765"
HA_URL="http://192.168.1.203:8123"

print_usage() {
    echo "Usage: sudo $0 [install|uninstall|status|logs|configure]"
    echo ""
    echo "Commands:"
    echo "  install   - Install and start the service"
    echo "  uninstall - Stop and remove the service"
    echo "  status    - Show service status"
    echo "  logs      - Show recent logs"
    echo "  configure - Reconfigure the service (token, IPs, etc.)"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo "Error: This script must be run as root (use sudo)"
        exit 1
    fi
}

configure_env() {
    echo ""
    echo "=== Configuration ==="
    echo ""

    # Read existing values if env file exists
    if [ -f "$ENV_FILE" ]; then
        source "$ENV_FILE"
    fi

    # Prompt for HA token
    echo "Home Assistant long-lived access token:"
    if [ -n "$HA_TOKEN" ]; then
        echo "(current: ${HA_TOKEN:0:10}...)"
    fi
    read -p "Enter token (or press Enter to keep current): " new_token
    if [ -n "$new_token" ]; then
        HA_TOKEN="$new_token"
    fi

    if [ -z "$HA_TOKEN" ]; then
        echo "Error: HA_TOKEN is required"
        exit 1
    fi

    # Prompt for Jetson host
    read -p "Jetson host IP [$JETSON_HOST]: " new_jetson_host
    if [ -n "$new_jetson_host" ]; then
        JETSON_HOST="$new_jetson_host"
    fi

    # Prompt for HA URL
    read -p "Home Assistant URL [$HA_URL]: " new_ha_url
    if [ -n "$new_ha_url" ]; then
        HA_URL="$new_ha_url"
    fi

    # Write env file (readable only by root)
    cat > "$ENV_FILE" << EOF
# Voice Assistant Configuration
# Generated by setup_pi_service.sh

HA_TOKEN=${HA_TOKEN}
HA_URL=${HA_URL}
JETSON_HOST=${JETSON_HOST}
JETSON_PORT=${JETSON_PORT}
HA_ENTITIES_PATH=${ENTITIES_PATH}
EOF

    chmod 600 "$ENV_FILE"
    echo ""
    echo "Configuration saved to $ENV_FILE"
}

install_service() {
    echo "=== Installing Voice Assistant Pi Client ==="

    # Verify paths exist
    if [ ! -d "$INSTALL_DIR" ]; then
        echo "Error: Install directory not found: $INSTALL_DIR"
        exit 1
    fi

    if [ ! -f "${VENV_PATH}/bin/python" ]; then
        echo "Error: Virtual environment not found: $VENV_PATH"
        exit 1
    fi

    if [ ! -f "$ENTITIES_PATH" ]; then
        echo "Warning: Entities file not found: $ENTITIES_PATH"
        echo "Make sure the entity sync cron job is running."
    fi

    # Configure if env file doesn't exist
    if [ ! -f "$ENV_FILE" ]; then
        configure_env
    else
        echo "Using existing configuration from $ENV_FILE"
        echo "(Run 'sudo $0 configure' to change settings)"
    fi

    # Create journal config directory if needed
    mkdir -p /etc/systemd/journald.conf.d

    # Configure journal size limits
    echo "Configuring journal size limits..."
    cat > "$JOURNAL_CONF" << 'EOF'
# Voice Assistant journal limits
# Prevents transcription logs from filling disk
[Journal]
SystemMaxUse=100M
SystemMaxFileSize=10M
MaxRetentionSec=7day
EOF

    # Restart journald to apply changes
    systemctl restart systemd-journald

    # Create systemd service file
    echo "Creating systemd service..."
    cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Voice Assistant Pi Client (Audio Capture + HA Control)
After=network.target sound.target
Wants=network-online.target

[Service]
Type=simple
User=${ACTUAL_USER}
Group=${ACTUAL_USER}
WorkingDirectory=${INSTALL_DIR}

# Load environment from file
EnvironmentFile=${ENV_FILE}

# Additional environment
Environment="PATH=${VENV_PATH}/bin:/usr/local/bin:/usr/bin:/bin"

# Command
ExecStart=${VENV_PATH}/bin/python run_pi.py \\
    --jetson-host \${JETSON_HOST} \\
    --jetson-port \${JETSON_PORT} \\
    --ha-url \${HA_URL} \\
    --ha-token \${HA_TOKEN} \\
    --entities \${HA_ENTITIES_PATH}

# Restart policy
Restart=always
RestartSec=5

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

# Audio access
SupplementaryGroups=audio

# Resource limits
Nice=-5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

    # Reload systemd and enable service
    echo "Enabling service..."
    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME"

    # Add user to audio group if not already
    if ! groups "$ACTUAL_USER" | grep -q audio; then
        echo "Adding $ACTUAL_USER to audio group..."
        usermod -a -G audio "$ACTUAL_USER"
    fi

    # Start service
    echo "Starting service..."
    systemctl start "$SERVICE_NAME"

    # Show status
    sleep 2
    systemctl status "$SERVICE_NAME" --no-pager || true

    echo ""
    echo "=== Installation Complete ==="
    echo ""
    echo "Useful commands:"
    echo "  sudo systemctl status $SERVICE_NAME   # Check status"
    echo "  sudo systemctl restart $SERVICE_NAME  # Restart"
    echo "  sudo systemctl stop $SERVICE_NAME     # Stop"
    echo "  sudo journalctl -u $SERVICE_NAME -f   # Follow logs"
    echo "  sudo journalctl -u $SERVICE_NAME -n 50 # Last 50 lines"
    echo "  sudo $0 configure                     # Change settings"
}

uninstall_service() {
    echo "=== Uninstalling Voice Assistant Pi Client ==="

    # Stop service if running
    if systemctl is-active --quiet "$SERVICE_NAME"; then
        echo "Stopping service..."
        systemctl stop "$SERVICE_NAME"
    fi

    # Disable service
    if systemctl is-enabled --quiet "$SERVICE_NAME" 2>/dev/null; then
        echo "Disabling service..."
        systemctl disable "$SERVICE_NAME"
    fi

    # Remove service file
    if [ -f "$SERVICE_FILE" ]; then
        echo "Removing service file..."
        rm -f "$SERVICE_FILE"
    fi

    # Remove journal config
    if [ -f "$JOURNAL_CONF" ]; then
        echo "Removing journal config..."
        rm -f "$JOURNAL_CONF"
    fi

    # Ask about env file
    if [ -f "$ENV_FILE" ]; then
        read -p "Remove configuration file (contains HA token)? [y/N]: " remove_env
        if [ "$remove_env" = "y" ] || [ "$remove_env" = "Y" ]; then
            rm -f "$ENV_FILE"
            echo "Configuration file removed."
        else
            echo "Configuration file kept at $ENV_FILE"
        fi
    fi

    # Reload systemd
    systemctl daemon-reload

    echo ""
    echo "=== Uninstallation Complete ==="
    echo "Note: The application files in $INSTALL_DIR were not removed."
}

show_status() {
    systemctl status "$SERVICE_NAME" --no-pager
}

show_logs() {
    journalctl -u "$SERVICE_NAME" -n 100 --no-pager
}

# Main
check_root

case "${1:-}" in
    install)
        install_service
        ;;
    uninstall)
        uninstall_service
        ;;
    status)
        show_status
        ;;
    logs)
        show_logs
        ;;
    configure)
        configure_env
        if systemctl is-active --quiet "$SERVICE_NAME"; then
            echo "Restarting service to apply changes..."
            systemctl restart "$SERVICE_NAME"
        fi
        ;;
    *)
        print_usage
        exit 1
        ;;
esac
